Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  # --- Server A (Subnetz 1) ---
  config.vm.define "nginx" do |nginx|
    nginx.vm.hostname = "nginx"
    nginx.vm.network "private_network", ip: "192.168.121.20"
    
    nginx.vm.provider :libvirt do |lv|
      lv.memory = 2048
      lv.cpus = 2
    end

    nginx.vm.provision "ansible" do |ansible|
      ansible.playbook = "nginx.yml"
      ansible.compatibility_mode = "2.0"
      ansible.extra_vars = {
        ansible_python_interpreter: "/usr/bin/python3"
      }
    end
  end
end